title: Vindicta Player Guide
description: "The player guide for the Arma 3 modification Vindicta: Guerrilla Warfare."
remote_theme: pmarsceill/just-the-docs


# Theme settings:
color_scheme: "dark"
logo: 'https://user-images.githubusercontent.com/1453936/73617285-e1372800-4614-11ea-81a1-5abe83abfe19.png'

# Aux links for the upper right navigation
aux_links:
  "Steam Workshop Page":
    - "//steamcommunity.com/sharedfiles/filedetails/?id=1964186045"
  "Discord":
    - "//discord.gg/CPkgHuN"
  "BI Forum Page":
    - "//forums.bohemia.net/forums/topic/227302-mpcoop-vindicta-alpha/"
  "GitHub Page":
    - "//github.com/Sparker95/Vindicta"

# Footer content appears at the bottom of every page's main content
footer_content: '<a href="{{site.github.repository_url}}/edit/master/{{page.path}}">Edit this page</a>'

search_enabled: true
